services:
  - type: web
    name: cognitick-api
    env: python
    plan: free
    branch: main
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://khajan_bhatt:Tanuj%4024042005@khajan38.9iqi4n1.mongodb.net/